- README.md
made readme a bit more straightforward
> chore: cleaner readme

- lua/guard/init.lua
...So that it would not complain when auto-format is already disabled.
> use pcall for GuardDisable

- README.md
- lua/guard/tools/linter/shellcheck.lua
> feat(linter): shellcheck

- README.md
Because guard should be focused on being minimal while allowing for easy customizability and extensibility, I figured the README should be revamped to emphasize this fact.
I think showing how easy it is to provide a custom config will persuade more people to keep using the plugin before they're dissuaded by their tool not being shown in the defaults.
Linters, however, are another story.
> feat(docs): revamp readme to focus on customizability

- lua/guard/filetype.lua
- lua/guard/spawn.lua
support env var spec like so:
```lua
ft('cpp'):fmt('clang-format'):env({ A = 'b' })
```
maintains existing env vars (does not override other than what's specified)
> feat(#44): support env var specification

- lua/guard/events.lua
- lua/guard/filetype.lua
- lua/guard/tools/formatter.lua
- lua/guard/tools/linter/shellcheck.lua
- test/filetype_spec.lua
a commit changed clang-format's default so the :extra test fails
> chore: fix ci tests again

- lua/guard/spawn.lua
When running in au print is silent, so no exe error was not shown.
> fix: silent error message

- lua/guard/spawn.lua
#68 warrants a bit more discussion about the exit code. While formatters exit with 0 (usually) on success, some linters like shellcheck exit with non-zero exit codes if they find errors. This means the following code, if put in spawn.lua, will not work if placed in function spawn() for some linters, but *will* resolve issue #68 by catching the exit code:
```lua
if exit_code == 0 then
coroutine.resume(co, table.concat(chunks))
else
on_failed(('process %s exited with non-zero exit code %s'):format(opt.cmd, exit_code))
coroutine.resume(co)
return
end
```
As a result, I think a check_exit_code is necessary. I don't like to introduce complexity but it's either add the function or somehow distinguish between linters and formatters before spawn(), which sounds like it could get messy. thoughts …
> fix(#68): handle formatter errors

- lua/guard/lint.lua
- lua/guard/tools/linter/selene.lua
linters sometimes use config files to know how to format - optional cwd() field passed to uv.spawn() supports this.
Most of this code will go into guard-collection in future
Planning to refactor linting out to make a lot easier in guard-collection. Going to stop all these prs for tools - need to focus on testing after this.
PR also uses cwd() in a demo with selene linter.
> feat(lint): support selene

- lua/guard/tools/formatter.lua
Black will output some stderr (`All done! ✨ 🍰 ✨`) without it and that was causing guard to think there was an error.
With --quiet, black does not output this success message but still does output error messages when there are any.
> Use --quiet for the black formatter

- README.md
- lua/guard/tools/formatter.lua
Nixfmt is a formatter for Nix. See https://github.com/serokell/nixfmt
> Adding support for nixfmt

- lua/guard/health.lua
excluding tables without the `cmd` field
> fix: checkhealth

- lua/guard/lint.lua
This change is prompted by a change in the python linter ruff. The json output has changed a bit and the severity no longer simply parsed. Example:
```python
import random
```
```json
[
{
"code": "F401",
"message": "`random` imported but unused",
"fix": {
"applicability": "Unspecified",
"message": "Remove unused import: `random`",
"edits": [
{
"content": "",
"location": {
"row": 1,
"column": 1
},
"end_location": {
"row": 2,
"column": 1
}
}
]
},
"location": {
"row": 1,
"column": 8
},
"end_location": {
"row": 1,
"column": 14
},
"filename": "/tmp/tmp.zV0Bmo7zZd/tmp.py",
"noqa_row": 1
}
]
```
By making all `attributes` in `from_json` a function or a key to the json message table, we can again extract the severity.
The new ruff config would be something like this:
```lua
{
cmd = "ruff",
args = …
```
> feat(lint): let attributes be functions

- lua/guard/events.lua
- lua/guard/format.lua
- lua/guard/init.lua
- plugin/guard.lua
diff update has bug .back to update whole buffer
> change diff update to whole buffer

- lua/guard/spawn.lua
resolves #111 - `uv.spawn()` fails to detect programs as executable on windows. Use `exepath()` to resolve paths before spawn.
> fix(#111): resolve windows executable paths

- doc/guard.nvim.txt
- lua/guard/format.lua
- lua/guard/lint.lua
> fix: splitting crlf lines

- doc/guard.nvim.txt
- lua/guard/events.lua
- lua/guard/format.lua
- spec/filetype_spec.lua
> fix: don't use error(...)

- doc/guard.nvim.txt
- lua/guard/events.lua
- lua/guard/format.lua
- plugin/guard.lua
> fix: impure formatting, lsp fallback not applied on load

- lua/guard/lint.lua
Ensure that the linter output is correctly assigned to the `data` variable when the output is not an error. This fixes a potential issue where the `data` variable could be left empty even when the linter produces valid output.
> fix(lint): handle linter output correctly

- CUSTOMIZE.md
- doc/guard.nvim.txt
- lua/guard/_meta.lua
- lua/guard/format.lua
- lua/guard/util.lua
- spec/format_spec.lua
- spec/lint_spec.lua
- spec/settings_spec.lua
> feat: args can be a function
